apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xco5estjf-python 
  janus-idp.io/tekton: xco5estjf-python
  backstage.io/kubernetes-id: xco5estjf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xco5estjf-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  